name: Andrei Nicholson
description: "Web developer and UI designer."
email: contact@andreinicholson.com

twitter_username: tetsuo13
github_username: tetsuo13
flickr_link: 90329256@N00
instagram_username: tetsuo13
linkedin_link: andrei-nicholson/6/697/2a4

url: http://andreinicholson.com
sass:
  style: :compressed

exclude:
    - README.md

