baseURL = 'https://andreinicholson.com/'
languageCode = 'en-us'
title = 'Andrei Nicholson'
enableRobotsTXT = true

# Disable the <meta name="generator" content="Hugo 0.74.3" /> tag.
disableHugoGeneratorInject = true

# Disable category and tag pages.
disableKinds = ["taxonomy"]

[params]
  description = 'Software developer and UI designer.'
  author = 'Andrei Nicholson'
  email = 'contact@andreinicholson.com'
  gitHubUsername = 'tetsuo13'
  flickrPhotostream = '90329256@N00'
  linkedInProfile = 'andrei-nicholson-2a46976'
