baseURL = "https://andreinicholson.com/"
languageCode = "en-us"
title = "Andrei Nicholson"
enableRobotsTXT = true

# Disable the <meta name="generator" content="Hugo 0.74.3" /> tag.
disableHugoGeneratorInject = true

# Disable category and tag pages.
disableKinds = ["taxonomy"]

[params]
  description = "Software developer and UI designer."
  author = "Andrei Nicholson"
  email = "contact@andreinicholson.com"

[permalinks]
  [permalinks.page]
    blog = "/blog/:year/:month/:day/:slug"

[markup]
  # https://gohugo.io/content-management/syntax-highlighting/
  [markup.highlight]
    # https://gohugo.io/quick-reference/syntax-highlighting-styles/
    style = "github"

